version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - doc
    - sphinxcontrib.applehelp==1.0.7
      
sphinx:
  configuration: docs/source/conf.py
